In [1]:
import json
from pathlib import Path
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport
from pandas_profiling.utils.cache import cache_file

In [2]:
file_name = cache_file(
    "census_train.csv",
    "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
)

In [3]:
# Names based on https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names
df = pd.read_csv(
    file_name,
    header=None,
    index_col=False,
    names=[
        "age",
        "workclass",
        "fnlwgt",
        "education",
        "education-num",
        "marital-status",
        "occupation",
        "relationship",
        "race",
        "sex",
        "capital-gain",
        "capital-loss",
        "hours-per-week",
        "native-country",
    ],
)

In [4]:
# Look at the head of the data
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

In [ ]:
df.tail()

Some of the variables are not self-explanatory. 

- age:the age of an individual.
Integer greater than 0

- workclass: a general term to represent the employment status of an individual.
It takes one of teh following values: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State- gov,
Without-pay, Never-worked.

- fnlwgt: final-weight. In other words, this is the number of people the census believes the entry represents.
Integer greater than 0

- education: the highest level of education achieved by an individual.
It takes one of eth following values: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc,
9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool. 

- education-num: the highest level of education achieved in numerical form.
Integer greater than 0

- marital-status: marital status of an individual. Married-civ-spouse corresponds to acivilian spouse while Married-AF-spouse is a spouse in the Armed Forces.
It takes one of the following values: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.

- occupation: the general type of occupation of an individual.
It iakes one of the following values: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial,
Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.

- relationship: represents what this individual is relative to others. For example an individual could be a Husband. Each entry only has one relationship attribute and is somewhat redundant with marital status. We might not make use of this attribute at all.
It iakes one of the following values: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried. 

- race: Descriptions of an individual’s race.
It iakes one of the following values: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black. 

- sex: the biological sex of the individual.
It iakes one of the following values: Male, Female

- capital-gain: capital gains for an individual. capital_gain is income from investment sources other than wage/salary.
Integer greater than or equal to 0. 

- capital-loss: capital loss for an individual. capital_gain ise income loss from investment sources other than wage/salary.
Integer greater than or equal to 0.

- hours-per-week: the hours an individual has reported to work per week.
continuous.

- native-country: country of origin for an individual
It iakes one of the following values: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam, USVI etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

In [5]:
# Statistics about the datasets can be obtained using the dataframe method describe()
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

## A more thorough profiling of the dataset can be performed using pandas-profiling

In [ ]:
# Prepare missing values
# Specifically, replace every cell value "?" with nan (not a number) ti be treated like a missing value 
df = df.replace("\\?", np.nan, regex=True)

In [ ]:
# Initialize the report
profile = ProfileReport(df, title="Census Dataset", explorative=True)

In [ ]:
# Specify the output html file
profile.to_file(Path("./census_report.html"))

### Go now an diplay the generated HTML file using your favorite browser.